### ISSUE TITLE
no timestamp and no location on both android and ios 

### ISSUE THREAD

**Issue by OritKedem** [react-native-image-picker/react-native-image-picker#1359]
using the latest version of react-native-image-picker
launchImageLibrary => no timestamp and no location on ios
launchCamera=> no timestamp and no location on both ios & android 

Please assist

**Comment by levipro** [comment]
This is because of the check on this line https://github.com/react-native-community/react-native-image-picker/blob/master/ios/ImagePickerManager.m#L207

Permissions to the photo library are not requested for newer iOS version. So you don't need permissions to select an image from the Library but you need permissions to get timestamp and location dataa

**Comment by YosefOberlander** [comment]
@levipro any updates?

**Comment by adimshev** [comment]
+1

**Comment by bhd119** [comment]
+1

**Comment by ravirajn22** [comment]
timestamp and location properties no longer supported in response. Open a new feature request issue with details and use case. Thanks
