### ISSUE TITLE
App crashed when pick image from gallery

### ISSUE THREAD

**Issue by praba1989** [react-native-image-picker/react-native-image-picker#1398]
this is error log

Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/1188/ORIGINAL/NONE/image/jpeg/1109518690 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F1188/ORIGINAL/NONE/image%2Fjpeg/1109518690} }} to activity {com././MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference

Thanks in Advance

**Comment by valsan** [comment]
#### Just some information, not a solution.

I had the same problem and realised only later it didn't have anything to do with this library.
The problem was caused by another library intercepting an ActivityEvent dispatched by the `ImagePickerModule`, effectively making the app crash.

Check your logs "thoroughly" to see if you have a similar problem, patching the other's library event listener (`onActivityResult`) by making it exclude unwanted events fixed this for me.

Hope it can help

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by cpecorari** [comment]
Hi, had the issue too (on v3.0.0-vnext.2), i can confirm it is gone on v3.0.0-vnext.4 ! 
Thanks a lot 🌈
