### ISSUE TITLE
[🌟] Bring back mixed media type in v3

### ISSUE THREAD

**Issue by xamoulin** [react-native-image-picker/react-native-image-picker#1527]
### Description

Support mixed media type like in V2.

### Proposed Solution

Accept `mixed` as a `mediaType` in `launchCamera` and `launchImageLibrary` like in v2

**Comment by ravirajn22** [comment]
What is the use case for having `mixed` type? Can you pitch your use case. If your case feels valid then I will put effort to implement.

**Comment by xamoulin** [comment]
Well, I use the picker to add a photo or a video as an attachment to a message. I could ask the user to select what kind of media he wants earlier but it feels it would do a better UX if he could select it directly in the camera view like he's used to. Also, given he changes his mind, it's quicker to change media type directly in the camera instead of going back to the previous view. I'm currently using the version 2.3.0 of this lib and it's working but I'd like to migrate to the supported version.

Thanks for taking some time to look at my request :)

**Comment by theill** [comment]
I really feel this needs to be including as a breaking change in the readme change log. I didn't realised the `mixed` mode was completely removed until after I already upgraded the library.

**Comment by RigoTheDev** [comment]
@theill Yep. Threw away my whole commit

**Comment by crobinson42** [comment]
This is a major bummer with the new version 3 release. I don't understand why this option would be removed from a mobile workflow? I work with several apps that require this as an option.

Use Case:

> As a User I can select the "camera" btn to take a photo or video or I can select the photo gallery to pick a saved photo or video

Without this feature, the UI requires an additional button for the user to select a video, this is not ideal because it requires a lot of UI component changes.

@ravirajn22

**Comment by jeffbonasso-ambifi** [comment]
I upvote as well. At minimum, it seems like when launching the gallery it definitely is beneficial that the gallery shows both the users photos and videos to choose from. Otherwise it requires adding separate buttons for an image gallery or video gallery. I know in iOS you can just pass an array of media types to the picker so it doesn't filter. Maybe you are saying Android isn't as easy.

**Comment by tgreco** [comment]
This needs to be brought back, library is dumb without it.

**Comment by julienR2** [comment]
Upvoting this as well as we offer our users to upload any kind of content and having them to chose between audio and video for the same flow isn't the best experience we can provide.

I see the issue is tagged with `Help wanted`, any details on what's needed and how we could help with it ? (I understand it's something that has been dropped from the previous version. Any technical reason behind the decision ?)
 I'd be keen to give a hand here if needed !

**Comment by benzman81** [comment]
@ravirajn22 why is the PR only for image library. Mixed should also be able for "capture". As a User it would be better to select the "camera" btn to take a photo OR video. Providing two buttons is not that nice.

**Comment by ravirajn22** [comment]
There is no support for it android.

**Comment by benzman81** [comment]
@ravirajn22 may be you can just document, that it is only for iOS then, just like you did for video quality medium?

**Comment by nandinicbit1981** [comment]
With 3.7.0 if i used mixed type i am seeing only video in the gallery.

**Comment by Johan-dutoit** [comment]
@nandinicbit1981, mixed works in the example app, if you want to check that out as a reference? 
If that doesn't help and you're still facing an issue, please create a new issue with as many details as possible.
