### ISSUE TITLE
[🐛] Limited permission not work for iOS

### ISSUE THREAD

**Issue by nicolasdevienne** [react-native-image-picker/react-native-image-picker#1749]
Limited permission not work for iOS. When I ask user to choose permission to access Library, he can choose all photos or just 1, 2 or 3 photos for example. When he choose just 1, 2 or 3 photos, just after, launchImageLibrary shows all photos in Library. No filter is apply.

Can you help me ?

**Comment by jeeyunlee-fe** [comment]
same issue here.

**Comment by hoony11** [comment]
same issue here. 

https://github.com/react-native-image-picker/react-native-image-picker/blob/1878acbca5ca40873cdbe047869f2e6337b28b49/ios/ImagePickerManager.m#L283

iOS 14 Limited permission not support

**Comment by tomgransden** [comment]
I get the permission dialog after taking a photo with saveToPhotos: true. Selecting some photos has no effect the next time I use launch the image library.

**Comment by ndevienne** [comment]
react-native-image-crop-picker works perfectly for iOS ! :)

**Comment by hazyikmis** [comment]
-> Has anybody found any workaround for this?

(Sorry but this library is unusable for ios without fixing this issue.)

**Comment by thibmaek** [comment]
Did my best Obj-C effort to integrate limited photo support here: https://github.com/react-native-image-picker/react-native-image-picker/pull/1814

**Comment by MusabBasheer** [comment]
any update

**Comment by cancerberoSgx** [comment]
Any updates on this issue ? The library is awesome but this issue is critical for our users. Thanks

**Comment by thatgriffith** [comment]
I'm also looking for this feature. Any updates? 🙂

**Comment by gurbela** [comment]
any news?

**Comment by thatgriffith** [comment]
We decide to use https://github.com/ivpusic/react-native-image-crop-picker instead. Works like a charm!

**Comment by FadiAboMsalam** [comment]
Any suggestion for this ????

**Comment by thatgriffith** [comment]
> Any suggestion for this ????

We switched to https://github.com/ivpusic/react-native-image-crop-picker and it works fine now.

**Comment by jeromegrosse** [comment]
Any update on that other than changing library? `react-native-image-crop-picker` have issues on its own such as GIF support on iOS.

**Comment by navaspavil** [comment]
Any update on this?

**Comment by fellipesnoww** [comment]
Any update on this?

**Comment by Johan-dutoit** [comment]
Would happily review PRs that solve this.

**Comment by Johan-dutoit** [comment]
Technically, the way image-picker works is correct.  Just because limited access has been selected, doesn't affect the photos displayed when calling `launchImageLibrary`.  That's how it natively works.

This can be seen all over the Apple forums and Stack overflow
- https://developer.apple.com/forums/thread/663098
- https://developer.apple.com/forums/thread/658485
- https://stackoverflow.com/questions/63369948/ios-14-still-display-entire-photo-library-despite-of-limited-status

A new method to prompt for additional photos would be useful though.

**Comment by Johan-dutoit** [comment]
Technically, the way image-picker works is correct.  Just because limited access has been selected, doesn't affect the photos displayed when calling `launchImageLibrary`.  That's how it natively works.

This can be seen all over the Apple forums and Stack overflow
- https://developer.apple.com/forums/thread/663098
- https://developer.apple.com/forums/thread/658485
- https://stackoverflow.com/questions/63369948/ios-14-still-display-entire-photo-library-despite-of-limited-status

A new method to prompt for additional photos would be useful though.

**Comment by Johan-dutoit** [comment]
https://github.com/react-native-image-picker/react-native-image-picker/pull/2157

**Comment by jameskim917** [comment]
@Johan-dutoit I can still access images that weren't given permissions though. So the picker does not limit the photos to the ones that have been given permission.

**Comment by franbe7** [comment]
Hey @Johan-dutoit, How [react-native-permissions](https://github.com/zoontek/react-native-permissions) solve this issue? 
The only related thing they provide is the method [openLimitedPhotoLibraryPicker](https://github.com/zoontek/react-native-permissions#openlimitedphotolibrarypicker-ios-14) which is for updating the selected photos, not for picking one.

**Comment by maksim14174** [comment]
#2093

**Comment by NiharR27** [comment]
Facing this issue as well @Johan-dutoit. Would you please be able to direct to what changes do we need to add from [react-native-permissions](https://github.com/zoontek/react-native-permissions) library? Or is it just sorted internally with the upgrades? Thanks 🙏🏽

**Comment by fxricky** [comment]
is there any solution for this? this doesn't seems fit into the terms "Selected photos"...

**Comment by Lakston** [comment]
Any updates on this ?

**Comment by sarveshhh-m** [comment]
@nicolasdevienne The react-native-image-crop-picker works perfectly unless we pick larger video.

**Comment by maziz-star** [comment]
same issue here - any update 

Or should i have to switch react-native-image-crop-picker

**Comment by nicolasdevienne** [comment]
Move to [Expo ImagePicker](https://docs.expo.dev/versions/latest/sdk/imagepicker/)
