### ISSUE TITLE
[🐛] Image picker not working for Android 13(Tiramasu).  

### ISSUE THREAD

**Issue by hardibhalodiya** [react-native-image-picker/react-native-image-picker#2130]
[🐛] Image picker not working when we are capturing image Using camera for Android 13(Tiramasu). 
After given permission for camera but camera is not opening.
Please anyone find any solution let me know.

**Comment by BishalftSaikia** [comment]
upgrade your sdk to version 33 which include Tiramasu configs ,` compileSdkVersion = 33  targetSdkVersion = 33`

**Comment by mohammadgharouni** [comment]
i'm having the same issue

**Comment by BishalftSaikia** [comment]
the same issue is happening on react-native-gesture-handler library, its not the library its the native side, also once i upgraded the sdk it was resolved, ref: [stackoverflow](https://stackoverflow.com/questions/75158364/error-cannot-find-symbol-if-build-version-sdk-int-build-version-codes-tirami)

**Comment by JKeddo95** [comment]
This guide helped me, I was missing class declaration in main application.java. Please reach out to the OP and thank him if this solves your issue too! :) 

https://c1ctech.com/react-native-image-picker-example/#:~:text=1%20Start%20a%20new%20React%20Native%20project.%20If,library%20you%20would%20see%20message%20like%20below%20screenshot.

**Comment by Siliconvelly** [comment]
I am using react-native-image-picker library since 1 year and suddenly i found the issue that samsung galaxy s22 ultra and s23 ultra unable to open camera. i can open gallery though this library but can't open camera so the maintainer have to fix this issue as soon as possible also i tried with new version of this library v5.4.2 and still not working.
today i got new version of this library and getting error after installing and run the application getting error  like

Calling `[node, /Users/adadminmin/cam_industrial_rn70/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

this kind of error if i use later version of below the latest one (5.6.0) then the error is not showing but if i use the latest 5.6.0 then i got this error.
so what is solution for working camera on samsung galaxy s22 ultra and samsung ultra s23.

**Comment by Johan-dutoit** [comment]
Example app works on Android 13.  Please ensure your project is setup in a similar fashion.  If it is and it's still not working, please share a reproducible demo.
